// =============================================================
// config/achievements.js — 成就系統定義（純資料，v1）
// =============================================================

export const ACHIEVEMENTS = [
    // ── beginner ────────────────────────────────────────────
    {
        id: 'first_play',
        name: '第一聲啼叫',
        description: '第一次進入遊戲',
        category: 'beginner',
        title: null,
        bonus: null,
    },
    {
        id: 'tutorial_done',
        name: '畢業了',
        description: '完成新手教學',
        category: 'beginner',
        title: null,
        bonus: null,
    },
    {
        id: 'first_death',
        name: '初嚐敗果',
        description: '第一次死亡',
        category: 'beginner',
        title: null,
        bonus: null,
    },
    {
        id: 'first_clear',
        name: '破殼而出',
        description: '首次通關任意難度',
        category: 'beginner',
        title: '大佬',
        bonus: null,
    },

    // ── clear ────────────────────────────────────────────────
    {
        id: 'clear_normal',
        name: '活過來了',
        description: '首次通關普通難度',
        category: 'clear',
        title: '獠牙',
        bonus: null,
    },
    {
        id: 'clear_10',
        name: '常勝鳥',
        description: '累積通關 10 次',
        category: 'clear',
        title: '老鳥',
        bonus: null,
    },
    {
        id: 'clear_hard',
        name: '黑羽精英',
        description: '首次通關困難難度',
        category: 'clear',
        title: '黑羽',
        bonus: null,
    },
    {
        id: 'clear_hell',
        name: '地獄生還者',
        description: '首次通關地獄難度',
        category: 'clear',
        title: '地獄噪鵑',
        bonus: null,
    },
    {
        id: 'no_damage_clear',
        name: '無傷通關',
        description: '任意難度不受傷通關',
        category: 'clear',
        title: null,
        bonus: null,
    },
    {
        id: 'speed_clear',
        name: '疾風',
        description: '任意難度 5 分 30 秒內通關',
        category: 'clear',
        title: '疾風鳥',
        bonus: null,
    },

    // ── boss ─────────────────────────────────────────────────
    {
        id: 'kill_black_bear',
        name: '暗黑瞎子',
        description: '首次擊殺黑熊王',
        category: 'boss',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_scorpion',
        name: '五毒之一',
        description: '首次擊殺沙漠蠍王',
        category: 'boss',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_shark',
        name: '白色死神',
        description: '首次擊殺大白鯊',
        category: 'boss',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_hunter',
        name: '獵人初見',
        description: '首次擊殺黑色獵人',
        category: 'boss',
        title: null,
        bonus: null,
    },
    {
        id: 'hunter_slayer',
        name: '獵人剋星',
        description: '困難模式擊殺黑色獵人 5 次',
        category: 'boss',
        title: '獵人的剋星',
        bonus: null,
    },
    {
        id: 'speed_kill_boss',
        name: '速殺',
        description: '60 秒內擊殺 Boss',
        category: 'boss',
        title: null,
        bonus: null,
    },

    // ── collect ──────────────────────────────────────────────
    {
        id: 'organ_collector',
        name: '器官收藏家',
        description: '解鎖全部器官槽（lv1 即可）',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'skill_master',
        name: '技能大師',
        description: '技能樹全滿',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'bone_500',
        name: '白骨精',
        description: '單局收集 500 根白骨',
        category: 'collect',
        title: '白骨精',
        bonus: null,
    },
    {
        id: 'fruit_2000',
        name: '果實狂人',
        description: '單局吃 2000 個果實',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'level_50',
        name: '我獨自升級',
        description: '單局達到 50 等',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_10000',
        name: '千殺',
        description: '累積擊殺 10000 隻普通怪',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_100_killer',
        name: '殺手中的殺手',
        description: '累積擊殺 100 隻殺手化怪',
        category: 'collect',
        title: null,
        bonus: null,
    },
    {
        id: 'kill_100_giant',
        name: '里維·阿卡曼',
        description: '累積擊殺 100 隻巨人',
        category: 'collect',
        title: null,
        bonus: null,
    },

    // ── character ────────────────────────────────────────────
    {
        id: 'koel_50',
        name: '噪鵑獠牙',
        description: '用噪鵑通關 50 次',
        category: 'character',
        title: null,
        bonus: null,
        condition: {
            type: 'characterClearCount',
            characterId: 'koel',
            threshold: 50,
        },
    },
    {
        id: 'archer_50',
        name: 'Biubiubiu',
        description: '用阿奇爾通關 50 次',
        category: 'character',
        title: null,
        bonus: null,
        condition: {
            type: 'characterClearCount',
            characterId: 'archerfish',
            threshold: 50,
        },
    },

    // ── growth ───────────────────────────────────────────────
    {
        id: 'veteran_days',
        name: '老玩家',
        description: '遊玩滿 30 天',
        category: 'growth',
        title: null,
        bonus: null,
    },
    {
        id: 'clear_100',
        name: '百戰老兵',
        description: '累積通關 100 次',
        category: 'growth',
        title: '百戰老兵',
        bonus: null,
    },
    {
        id: 'evo_5star',
        name: '進化完成',
        description: '單局達成 5⭐ 進化',
        category: 'growth',
        title: null,
        bonus: null,
    },
    {
        id: 'mutation_100',
        name: '變異怪物',
        description: '變異等級達到 100 級',
        category: 'growth',
        title: null,
        bonus: null,
    },

    // ── hidden ───────────────────────────────────────────────
    {
        id: 'pioneer',
        name: '先驅者',
        description: '早期玩家',
        category: 'hidden',
        title: '先驅者',
        bonus: null,
    },
    {
        id: 'win_streak_5',
        name: '五連殺',
        description: '連續 5 局不死且勝利',
        category: 'hidden',
        title: null,
        bonus: null,
    },
    {
        id: 'no_regen_clear',
        name: '野外求生',
        description: '困難難度通關但全程未回血',
        category: 'hidden',
        title: null,
        bonus: null,
    },
    {
        id: 'all_achievements',
        name: '完全體',
        description: '解鎖所有非隱藏成就（#1~#30）',
        category: 'hidden',
        title: '恐怖如斯',
        bonus: null,
    },
    {
        id: 'night_owl',
        name: '深夜鳥',
        description: '凌晨 0~4 點（GMT+8）遊玩',
        category: 'hidden',
        title: null,
        bonus: null,
    },
    {
        id: 'mutation_500',
        name: '我無敵了',
        description: '累積使用 500 次變異技能',
        category: 'hidden',
        title: '無敵',
        bonus: null,
    },
];
